import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Health Product 7',
      category: 'Powders',
      image: '/images/p7.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Pwder',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Health Product 8',
      category: 'Powders',
      image: '/images/p8.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Pwder',
      rating: 4.0,
      numReviews: 10,
      description: 'High quality product',
    },
    {
        name: 'Health Product 9',
        category: 'Powders',
        image: '/images/p9.jpg',
        price: 60,
        countInStock: 20,
        brand: 'Pwder',
        rating: 5.0,
        numReviews: 10,
        description: 'High quality product',
    },
    {
        name: 'Health Product 10',
        category: 'Powders',
        image: '/images/p10.jpg',
        price: 50,
        countInStock: 20,
        brand: 'Pwder',
        rating: 4.0,
        numReviews: 10,
        description: 'High quality product',
    },
    {
        name: 'Health Product 11',
        category: 'Health Supplements',
        image: '/images/p11.jpg',
        price: 100,
        countInStock: 20,
        brand: 'Pwder',
        rating: 4.0,
        numReviews: 10,
        description: 'High quality product',
    },
    {
        name: 'Health Product 12',
        category: 'Health Supplements',
        image: '/images/p12.jpg',
        price: 100,
        countInStock: 20,
        brand: 'Pwder',
        rating: 4.5,
        numReviews: 10,
        description: 'High quality product',
    },
  ],
};
export default data;
