const data = {
    products: [
        {
            _id: '1',
            name: 'Organic MultiVitamins',
            image: '/images/p1.jpg',
            price: 45,
            countInStock: 0,
            brand: 'organicx',
            rating:4.5,
            numReviews:14,
            description:'Organic Multivitamins blend pack with all the essential amino acids your body needs to maintain itself healthy.',

        },
        {
            _id: '2',
            name: 'Organic Spirulina Powder 32oz',
            image: '/images/p2.jpg',
            price: 28.99,
            countInStock: 15,
            brand: 'organicT',
            rating:4.5,
            numReviews:4,
            description:'High Quality Spirulina fine ground powder, incredibly healthy and delicious. Easy to add into smoothies , salads and more! ',
        },
        {
            _id: '3',
            name: 'Moringa Leaf Tea bag Kit',
            image: '/images/p3.jpg',
            price: 12.99,
            countInStock: 25,
            brand: 'organicx',
            rating:4.5,
            numReviews:8,
            description:'Moringa Leaf Tea bag Kit Moringa Leaf Tea bag Kit Moringa Leaf Tea bag Kit Moringa Leaf Tea bag Kit',
        },
        {
            _id: '4',
            name: 'Organic Tumeric Powder',
            image: '/images/p4.jpg',
            price: 23.99,
            countInStock: 15,
            brand: 'organicJ',
            rating: 5,
            numReviews:10,
            description:'Organic Tumeric Powder findley ground powder, incredibly healthy and easy to diversify your recipes. Blends well with smoothies and baking recipes. ',
        },
        {
            _id: '5',
            name: 'Organic Ashwagandha powder',
            image: '/images/p5.jpg',
            price: 28.99,
            countInStock: 15,
            brand: 'organicx',
            rating: 4.5,
            numReviews:13,
            description:'Ashwagandha is available in the form of powder, tablets, capsules and as a liquid extract. Traditionally, it is used as a dried powder which is combined with warm milk and honey to make a soothing drink. This mixture works well when taken before bedtime. It helps to calm mind and body, promoting healthy patterns of sleep and strength.',
        },
        {
            _id: '6',
            name: 'Organic Chlorella Powder',
            image: '/images/p6.jpg',
            price: 45,
            countInStock: 15,
            brand: 'organicJ',
            rating: 5,
            numReviews:10,
            description:'Chlorella Powder Organic (Chlorella Broken Cell Wall), 8 Ounce, No Irradiation and Vegan Friendly',
        },
        {
            _id: '7',
            name: 'Vitamin D3 ',
            image: '/images/p7.jpg',
            price: 45,
            countInStock: 5,
            brand: 'organicT',
            rating: 4.5,
            numReviews:105,
            description:'IMMUNE SUPPORT: 350-count, 1000IU Vitamin D3 Softgels for immune health.* Vitamin D by Nature’s Bounty may assist the immune system by helping to regulate T and B-lymphocytes.* Vitamin D3 is a more potent form of Vitamin D',
        },
        {
            _id: '8',
            name: 'Moringa Leaf Powder',
            image: '/images/p8.jpg',
            price: 24.99,
            countInStock: 10,
            brand: 'organicJ',
            rating: 5,
            numReviews:40,
            description:'Our Top Quality Potent Moringa Provides Energy, Strength and Stamina. Promotes Good Sleep, Digestion, Bones, Joints. Makes you Strong and Active. Increases the Natural Defenses of the body. Promotes Cell Structure of the body. Improves the Immune system. Rich in Antioxidants. Promotes a Healthy Circulatory system. Provides nourishment to the Eyes and Brain. Promotes Proper Digestion and Bowl Movement. Beautifies the Skin.',
        },
        {
            _id: '9',
            name: 'Organic Beet Powder Supplements',
            image: '/images/p9.jpg',
            price: 45,
            countInStock: 15,
            brand: 'organicT',
            rating:4.5,
            numReviews:70,
            description:'Most Versatile – Add Nutrition To Anything! PureBeets will save you a ton of money and a ton of time juicing. This super-fine powder Bolsters Nutrition at Every Meal, Blending Perfectly with water or your favorite beverage Without Clumping, plus Adding Natural Food Coloring; Brighter Flavors to your salad, cereal, toast, sauces, yogurt, ice cream and baked goods.',
        },
        {
            _id: '10',
            name: 'Organic Elderberry Syrup Making Kit',
            image: '/images/p10.jpg',
            price: 23.99,
            countInStock: 15,
            brand: 'organicT',
            rating:4.5,
            numReviews:50,
            description:' Elderberry+ is a delicious, organic blend of elderberry, echinacea, and licorice. It can be taken daily to maintain a healthy immune system or at the onset of symptoms.* Enjoy the delicious, natural flavor of Elderberry+ with no added sugar. Just mix with water or your favorite beverage for an immune-boosting punch.*',
        },
        {
            _id: '11',
            name: 'Organic Honey with Tumeric',
            image: '/images/p11.jpg',
            price: 24.99,
            countInStock: 12,
            brand: 'organicJ',
            rating:4.5,
            numReviews:10,
            description:'NATURE’S SWEETENER: Whether you need a sugar substitute for baking, a replacement for unhealthy snack toppings, or an all-natural sweetener for tea, our native Australian honey is the ideal choice.',
        },
    ],
};

export default data;